FROM eclipse-temurin:25.0.4_7-jdk-alpine-3.23@sha256:b7c88ce22d575642650ec83cbf4e470a0c183a46871467180238e4b27ad9e20a

ARG LIBHEIF_VERSION=1.23.0-r0

RUN apk add --no-cache \
        "libheif=${LIBHEIF_VERSION}" \
        "libheif-dev=${LIBHEIF_VERSION}" \
    && test -e /usr/lib/libheif.so \
    && test -e /usr/lib/libheif.so.1

ENV JAVA_TOOL_OPTIONS=--enable-native-access=ALL-UNNAMED
